apiVersion: apps/v1
kind: Deployment
metadata:
  name: chillphim-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chillphim
  template:
    metadata:
      labels:
        app: chillphim
    spec:
      containers:
        - name: chillphim-container
          image: chillphimacr2026phat.azurecr.io/chillphim:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chillphim-secrets
                  key: JWT_SECRET
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: chillphim-secrets
                  key: MONGO_URI
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: chillphim-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: chillphim-secrets
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: chillphim-secrets
                  key: CLOUDINARY_API_SECRET
